### ISSUE TITLE
Enhance golang SDK and test code to perform the detailed steps across multiple parties

### ISSUE THREAD

**Issue by jimthematrix** [hyperledger-labs/zeto#2]
The golang test code needs to prove that the necessary steps can be performed by the counterparties to obtain the ability to spend received tokens:
- decrypting values from the onchain events
- check if the decrypted values match the UTXO hashes, in order to judge that the UTXO is for me. If an encrypted value is not for a UTXO with me as the owner, then the decrypted value (a value is always recovered, whether the decrypting party has the right key or not) won't hash to the same UTXO in the transaction

**Comment by EnriqueL8** [comment]
@jimthematrix I've picked this one up, let me know if it's appropriate
