### ISSUE TITLE
JS test error

### ISSUE THREAD

**Issue by priyochatterjee08** [hyperledger-labs/zeto#28]
I am getting following errors in running js tests. Please help me resolve the issues.
1) main circuit tests for Zeto fungible tokens with anonymity without encryption
       should fail to generate a witness because mass conservation is not obeyed:
     AssertionError: expected Error: Error: Assert Failed.
Error in tem… to match /Error in template CheckHashesAndSum_89 line: 95/
      at Context.<anonymous> (test/anon.js:132:20)
2) main circuit tests for Zeto fungible tokens with anonymity without encryption
       should generate a valid proof that can be verified successfully:
     Error: Invalid witness length. Circuit: 5205, witness: 2061
      at Object.groth16Prove [as prove] (node_modules/snarkjs/build/main.cjs:900:15)
      at async Context.<anonymous> (test/anon.js:169:38)
3) main circuit tests for Zeto fungible tokens with anonymity with encryption
       should fail to generate a witness because mass conservation is not obeyed:
     AssertionError: expected Error: Error: Assert Failed.
Error in tem… to match /Error in template CheckHashesAndSum_89 line: 95/
      at Context.<anonymous> (test/anon_enc.js:145:20)
4) main circuit tests for Zeto fungible tokens with encryption and anonymity using nullifiers
       should fail to generate a witness because mass conservation is not obeyed:
     AssertionError: expected Error: Error: Assert Failed.
Error in tem… to match /Error in template CheckNullifierHashesAndSum_246 line: 156/
      at Context.<anonymous> (test/anon_enc_nullifier.js:271:20)
  5) main circuit tests for Zeto fungible tokens with anonymity using nullifiers and without encryption
       should fail to generate a witness because mass conservation is not obeyed:
     AssertionError: expected Error: Error: Assert Failed.
Error in tem… to match /Error in template CheckNullifierHashesAndSum_246 line: 156/
      at Context.<anonymous> (test/anon_nullifier.js:225:20)
  6) check-nullifiers circuit tests
       should fail to generate a witness because incorrect values are not used:
     AssertionError: expected Error: Error: Assert Failed.
Error in tem… to match /Error in template CheckNullifiers_155 line: 63/
      at Context.<anonymous> (test/check_nullifiers.js:119:20)

**Comment by Chengxuan** [comment]
fixed as part of https://github.com/hyperledger-labs/zeto/pull/27
