### ISSUE TITLE
github actions for e2e tests and hardhat tests

### ISSUE THREAD

**Issue by jimthematrix** [hyperledger-labs/zeto#29]
these tests depend on the generation of the WASM runtime and proving keys, which are now possible after #27 
- `js/test`
- `golang/integration-test`
- `solidity/test`

**Comment by EnriqueL8** [comment]
@jimthematrix feels to me that this issue is covered by https://github.com/hyperledger-labs/zeto/blob/main/.github/workflows/e2e.yaml ?

**Comment by jimthematrix** [comment]
yes indeed. fixed by #30
