### ISSUE TITLE
Add patterns that add encrypted values for a designated authority

### ISSUE THREAD

**Issue by jimthematrix** [hyperledger-labs/zeto#7]
For the use cases where a regulatory or central authority requires knowledge of the secrets of all new UTXOs

**Comment by EnriqueL8** [comment]
How similar is this to https://github.com/hyperledger-labs/zeto/pull/37?

**Comment by jimthematrix** [comment]
> How similar is this to https://github.com/hyperledger-labs/zeto/pull/37?

ha, it's now addressed by #37
