### ISSUE TITLE
Add event for lockProof()

### ISSUE THREAD

**Issue by jimthematrix** [hyperledger-labs/zeto#86]

**Comment by chbg** [comment]
Hi there, @jimthematrix ! 

I’m interested in contributing to this issue, but I would appreciate some clarification. Could you provide more details about what kind of event you would like to be added for lockProof()? Specifically:

	•	What data or parameters should the event emit?
	•	Are there any specific conditions or actions that should trigger the event?
	•	Is there a preferred naming convention or structure for events in this repo?

Thanks in advance for your guidance!

**Comment by jimthematrix** [comment]
@chbg hi Houston, thanks for offering to work on this! if the event includes the proof Hash and the delegate, I think we are in good shape. Looking forward to seeing a PR for this!

**Comment by jimthematrix** [comment]
@chbg hi Houston, want to give you a heads up that we have started thinking about moving away from the `lockProof()` approach in favor of locking the states, see https://github.com/hyperledger-labs/zeto/pull/110 for details.

**Comment by jimthematrix** [comment]
closing this as the PR for using `lockStates()` #110 has been merged
